### ISSUE TITLE
Docker startup fails if config path is a directory instead of a file

### ISSUE THREAD

**Issue by beirtipol** [czerwonk/ping_exporter#30]
I'm getting the following output when attempting to run the docker image with the same command line as suggested on the readme. I've saved a 'config.yml' file in the mounted volume.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x3daf70]

goroutine 1 [running]:
main.addFlagToConfig(0x0)
        /go/ping_exporter/main.go:236 +0x14
main.loadConfig(0x0, 0x0, 0x0)
        /go/ping_exporter/main.go:213 +0x100
main.main()
        /go/ping_exporter/main.go:78 +0x168
```

I spent some time trying to figure this out but it's simply that the '/config' path needs to point at the config.yml file, not at a directory containing the config.yml.

**Comment by keithpjolley** [comment]
as an example:
```
% ls config.yml
% docker run ... -v $(pwd)/config.yml:/config/config.yml:ro --name ...
```
